// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
insert into refresh_tokens(token, created_at, updated_at, user_id, expires_at)
values (
    $1,
    now(),
    now(),
    $2,
    date_add(now(), '60 days')
) returning token, created_at, expires_at
`

type CreateRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

type CreateRefreshTokenRow struct {
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.Token, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
select token, created_at, updated_at, user_id, expires_at, revoked_at from refresh_tokens
where token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
